### ISSUE TITLE
Issue downloading FSGKaggle2018

### ISSUE THREAD

**Issue by elcronos** [MTG/DCASE-models#21]
I'm trying to download the dataset FSDKaggle2018

```python
from dcase_models.data.datasets import FSDKaggle2018
dataset = FSDKaggle2018('../datasets/FSDKaggle2018')
dataset.download()
```

However I get the error:
```
FileNotFoundError: [Errno 2] No such file or directory:
datasets/FSDKaggle2018/meta/train_post_competition.csv
```

I have been able to download all other datasets except this one because of that error. Any suggestions?

**Comment by pzinemanas** [comment]
Hi! Thanks reporting these issues.

There is a bug in `FSDKaggle2018`. When initializing the instance, it is assumed that the dataset has been downloaded before and that is why it tries to open the `train_post_competition.csv` file. I'll fix it now.

**Comment by pzinemanas** [comment]
It should be working now. This fix will be included in the next release. For now, please install DCASE-models from the repository:

```
git clone https://github.com/MTG/DCASE-models.git
cd DCASE-models
pip install .
```
