### ISSUE TITLE
Error in train_model.py

### ISSUE THREAD

**Issue by elcronos** [MTG/DCASE-models#22]
There is a syntax error in the line 198 of the file train_model.py :

```python
# Train model
    model_container.train(
        data_gen_train, data_gen_val,
        # data_train, data_val,
        label_list=dataset.label_list,
        weights_path=exp_folder, **params['train'], # 198 Line
        sequence_time_sec=params_features['sequence_hop_time']
    )
```

Error:
File "train_model.py", line 198
    weights_path=exp_folder, **params['train'],
                                              ^
SyntaxError: invalid syntax

**Comment by pzinemanas** [comment]
Hi again, I've test it on Python 3.6 and it seems to be working. Please let me know which version of Python you are using.

**Comment by elcronos** [comment]
Hi Pablo,

Thanks for your prompt response. I create a conda env using Python 3.6.13 and installed the library for tensorflow 2:

```
pip install DCASE-models[tf2] # for tensorflow 2
```

I get that error when I run :
```
python train_model.py -d ESC50 -f MelSpectrogram -m SB_CNN -fold fold1
```

I think the error is just a syntax error because exp_folder is assigned to weights_path variable but **params['train] is not being assigned.

I hope it makes sense.

**Comment by pzinemanas** [comment]
That's weird because there is no syntax error. I've tried installing again from scratch and it is working. Note that if you want to use tensorflow2, you have install the library from the repository:

```
git clone https://github.com/MTG/DCASE-models.git
cd DCASE-models
pip install .[tf2]
```

**Comment by elcronos** [comment]
Thanks. Somehow reinstalling the library and downloading the repo again worked !
