### ISSUE TITLE
Issue when running visualization

### ISSUE THREAD

**Issue by elcronos** [MTG/DCASE-models#26]
Env: Using Python 3.6 and tensorflow 2.2.0
On my conda environment I got an error when running this inside my DCASE-models folder:

```
python -m visualization.index
```
Error:
```
from tensorflow import get_default_graph
ImportError: cannot import name 'get_default_graph'
```

**Comment by pzinemanas** [comment]
Hi @elcronos , it should be fixed now. Please note that visualization tools are not fully tested yet.

**Comment by elcronos** [comment]
Yeah, as you mentioned is working now but some of the functionalities aren't.
